version: "3"
services:
  backend:
    build:
      context: ./backend
    image: "backend:1"
    ports:
      - 3000:3000
  frontend:
    image: "nginx:1.16"
    volumes:
      - ./frontend:/usr/share/nginx/html/
    ports:
      - 80:80
